### ISSUE TITLE
模拟器5s 8.1系统 报错

### ISSUE THREAD

**Issue by a442914168** [iphone5solo/PYTheme#1]
报错如下：
unexpected nil window in _UIApplicationHandleEventFromQueueEvent, _windowServerHitTestWindow: <UIWindow: 0x7fa6ef72f960; frame = (0 0; 0 0); gestureRecognizers = <NSArray: 0x7fa6ef730460>; layer = <UIWindowLayer: 0x7fa6ef72fdb0>>

**Comment by a442914168** [comment]
解决：
self.window = [[UIWindow alloc]init];改为
self.window = [[UIWindow alloc]initWithFrame:[UIScreen mainScreen].bounds]; 
是因为window没有frame

**Comment by ko1o** [comment]
@a442914168  谢谢反馈！
