### ISSUE TITLE
模拟器 7 plus，不能运行 

### ISSUE THREAD

**Issue by wangquana7** [iphone5solo/PYTheme#4]
- (void)py_setThemeColor:(UIColor *)color 这个方法中的
 // 切换到主线程设置
   dispatch_sync(dispatch_get_main_queue(), ^{
  // 给对象的对应属性赋值（使用KVC）
          [object setValue:color forKeyPath:propertyName];
  });
这一句报错。

**Comment by ko1o** [comment]
@wangquana7  嗯嗯 是在抱歉，这个没处理好。已经撤回了，欢迎重新下载测试
