### ISSUE TITLE
demoCrash

### ISSUE THREAD

**Issue by zoujie10** [iphone5solo/PYTheme#5]
![b4fbe0f5-9f88-442a-89e4-4dae436bb569](https://cloud.githubusercontent.com/assets/12573719/21340712/4ed3737a-c6c3-11e6-82b4-1518b3c2dea9.png)

**Comment by ko1o** [comment]
@zoujie10  嗯嗯 是在抱歉，这个没处理好。已经撤回了，欢迎重新下载测试
