### ISSUE TITLE
关于自动内存管理的理解

### ISSUE THREAD

**Issue by zedzhao** [iphone5solo/PYTheme#7]
想确认下理解的对不对，
判断 retainCount = 2的对象是应该被release的对象的依据是， 在themeColorPool中有retain了一次， 然后在 copy的时候又retain了一次， 而其他正在使用的对象的retainCount一定是大于2的。 
这样理解对么?

> // 遍历主题色池(移除应该被回收的对象)
    for (NSDictionary *dict in [[self themeColorPool] copy]) {
        // 取出key
        NSString *objectKey = nil;
        for (NSString *key in [dict allKeys]) {
            if (![key isEqualToString:PYTHEME_COLOR_ARGS_KEY]) {
                objectKey = key;
                break;
            }
        }
        // 取出对象
        id object = [dict valueForKey:objectKey];
        // 取出对象的引用计数
        NSInteger retainCount = [[object valueForKey:@"retainCount"] integerValue];
        if (retainCount == 2) { // 对象应该被回收了
            [[self themeColorPool] removeObject:dict];
        }
    }

**Comment by ko1o** [comment]
@zedzhao  使用retainCount 还是不够合理的，现在最新的方案是采用NSMapTable对对象采取弱引用，具体讨论见：https://github.com/iphone5solo/PYTheme/issues/2
